### ISSUE TITLE
Add better colour support

### ISSUE THREAD

**Issue by Steadyx** [camspiers/snap#9]
Love this plugin, would be great if it had better colour support for different themes.

**Comment by astridlyre** [comment]
Yes! It would be nice to be have highlight groups for things like the selection row, which is kinda hard to see atm.

**Comment by LoydAndrew** [comment]
Hello, greate plugin. But what's that weird background (with some kind of opacity) in UI? I've checked with all popular themes like gruvbox, onedark, oceanic and it's there. 
![back](https://user-images.githubusercontent.com/28489428/122588744-1d332780-d068-11eb-97fb-984dbb8f1a6e.png)

**Comment by beauwilliams** [comment]
Yep would be great to customise I can't even see whats selected with mine. I think its just the highlights.

![image](https://i.ibb.co/GcwNhV9/Screen-Shot-2021-06-19-at-7-14-04-pm.png)

**Comment by camspiers** [comment]
I definitely need to work on this, thanks for all the feedback. I will prioritize it this coming week. 😊

**Comment by Steadyx** [comment]
legend

**Comment by camspiers** [comment]
Addressed in: https://github.com/camspiers/snap/commit/ee87275c0f99491fe3804bfa9fb76b7e42b778cc

Please let me know if you need any more customization.

You can define your own colors with:

```
SnapSelect
SnapMultiSelect
SnapNormal
SnapBorder
SnapPosition
SnapPrompt
```

But they all should now have more reasonable defaults from whatever colorscheme you are using.

**Comment by camspiers** [comment]
Please feel invited to provide more color feedback here, I will keep watching this issue, and in fact I will leave it open for a while. The defaults I have chosen seem reasonable and I have checked in a few themes where it seems to work well.

**Comment by LoydAndrew** [comment]
Hello, It's a lot better now, but it's still has vertical line 
![2021-06-20_12-18](https://user-images.githubusercontent.com/28489428/122668645-b88be000-d1c1-11eb-9aab-25973c6c1554.png)

**Comment by beauwilliams** [comment]
I've tried playing around with all the highlight settings, but I seem to be having this issue still. Not sure if its just me. Not able to see where the cursor is. https://github.com/camspiers/snap/issues/9#issuecomment-864380570

**Comment by camspiers** [comment]
@LoydAndrew that might be cursorcolumn highlighting. I'll have a look into it when I get time.

**Comment by camspiers** [comment]
@beauwilliams Are you sure you have updated? Unless your theme doesn't set a highlight for WildMenu it should no longer be an issue, and if your theme doesn't set a highlight for WildMenu it should (but otherwise you can set a default).

**Comment by beauwilliams** [comment]
I have just done a git pull and checked with :highlight, very odd seems that the group is set correctly and my wildmenu colours should be visible. That must not be the issue then ![image](https://i.ibb.co/DtVJq9K/Screen-Shot-2021-06-20-at-8-10-05-pm.png)

**Comment by camspiers** [comment]
@LoydAndrew I have resolved your cursorcolumn issue in https://github.com/camspiers/snap/commit/c9d6dcc516d096f022bd30d0bb2640a3253d44ea

**Comment by LoydAndrew** [comment]
Yeah, thanks it works. There is however a new issue C-u C-d keybindings stop working after new changes but that's separate issue.

**Comment by camspiers** [comment]
@LoydAndrew fixed in https://github.com/camspiers/snap/commit/bbd864b40e96b22459ff660e696a07e2f333392d
